<link rel="stylesheet" href="./public/css/bootstrap.min.css">
    <link rel="stylesheet" href="./public/css/fontawesome.min.css">
    <link rel="stylesheet" href="./public/css/all.min.css">
    <link rel="stylesheet" href="./public/css/header.css">
    <link rel="stylesheet" href="./public/css/modal.css">
    <link rel="stylesheet" href="./public/css/thongke.css">
    <link rel="stylesheet" href="./public/css/viewProfile.css">
    <link rel="stylesheet" href="./public/css/navContent.css">
    <link rel="stylesheet" href="./public/css/modalAdd.css">